package com.example.backstage.crs.util;

import com.example.backstage.crs.entity.TiceEntity;
import lombok.Data;

/**
 * Created by GuanYuCai on 2016/10/18 0018.
 */
@Data
public class Param {
    private String username;
    private String password;
    private Long accountid;
    private String accountname;
    private String isLogin;
    private String session_key;
    private String encryptedData;
    private String vi;
    private String jscode;
    private String userid;
    private String userInfo;
    private String rawData;
    private String signature;
    private String iv;
    private String unionid;
    private String name;
    private String phone;
    private String sex;
    private String storeid;
    private String saleuserid;
    private String remarks;
    private String coachid;
    private String courseid;
    private String date;
    private String ctype;
    private String cid;
    private String sid;
    private String cardid;
    private String amount;
    private String openid;
    private String prepayId;
    private String scheduleid;
    private String cardno;
    private String ordtype;
    private String traineenum;
    private String cat;
    private String tid;
    private String fee;
    private String buytype;
    private String feedcontents;
    private String goodscode;
    private String phonenum;
    private String code;
    private String orderid;
    private String searchvalue;
    private String euserid;
    private String contents;
    private String usertel;
    private String lastedby;
    private String birthday;
    private String homeaddress;
    private String workaddress;
    private String height;
    private String weight;
    private String fitnessgoal;
    private String fitnessexperience;
    private String qtype;
    private String curdate;
    private String weekbegin;
    private String weekend;
    private String monthbegin;
    private String monthend;
    private String datebegin;
    private String coursetype;
    private String courseimpression;
    private String impression;
    private String dateend;
    private String pricetid;
    private String coursetime;
    private String page;
    private String scene;
    private String refuserid;
    private String frms;
    private String pageindex;
    private String CourseDatestart;
    private String CourseDateend;
    private String limit;
    private String courseendtime;
    private String status;
    private String luckdrawid;
    private String recordid;
    private String points;
    private String createdby;
    private String createdname;
    private String schedulebegin;
    private String coursename;
    private String templatetype;
    private String cardname;
    private String time;
    private String day1;
    private String day2;
    private String strenth;
    private String courseduration;
    private String reservablenumber;
    private String minpeople;
    private String scheduledate;
    private String scheduleend;
    private String storename;
    private String coachname;
}
